### ISSUE TITLE
Why is the map on the "Visit" page a map of Madison?

### ISSUE THREAD

**Issue by vielmetti** [allhandsactive/site#197]
Noted at

https://allhandsactive.org/visit

see https://infosec.exchange/@AMS/112057418252744337

**Comment by l0gik** [comment]
If memory serves, this was someone's Actual AHA Laser Project.  Folks thought it was pretty neat, and decided to use it there as a kind of stock art, more due to its relevance to the visual concept of "location", even if not of Michigan or Ann Arbor.  If we had a similar lasered topo-map with a more local scope, we could put it in there... but nobody has created such a thing yet. :)
